### ISSUE TITLE
Support stubbing of constants

### ISSUE THREAD

**Issue by nepalez** [nepalez/fixturama#2]
Use the RSpec [`stub_const`](https://relishapp.com/rspec/rspec-mocks/v/3-8/docs/mutating-constants) method.

```yaml
---
# stub_const(“TIMEOUT_SEC”, 10)
- const: TIMEOUT_SEC
  value: 10
```
