### ISSUE TITLE
Update stubbing to support any objects, not only classes

### ISSUE THREAD

**Issue by nepalez** [nepalez/fixturama#5]
Now we can stub class/module methods only via fixture syntax:

```yaml
---
- class: Foo
  chain:
    - bar
    - baz
    - qux
  # ...
```

It would be nice to support the following syntax as well:

```yaml
---
- object: Foo.bar.baz
  chain:
    - qux
  # ...
```
