### ISSUE TITLE
Support partial definition of options

### ISSUE THREAD

**Issue by nepalez** [nepalez/fixturama#7]
This fixture

```yaml
---
- class: Foo
  chain: call
  arguments:
    - 1
    - :bar: 1
  actions:
    - return: 2
```

Should match both cases:

```ruby
Foo.call 1, bar: 1 # => 2
Foo.call 1, bar: 1, baz: 0 # => 2
```
